export const HeaderColor = '#002663';
export const HeaderFontColor = '#fff!important';
export const SidebarColor = '#002663';
export const CardBottom = 'linear-gradient(to right, #ff9900 , #ff9900)';
export const SubmitButton = '#fdab3b';
export const SubmitGradientButton ='linear-gradient(to top, #ff9900 , #ff9900)';
export const AppNameAdmin="Liwach Portal";
export const TitleColor = '#4d4f53';
export const text="#a3574c"
export const TitleSize = 45;
export const CardTitleColor = '#a3574c';
export const GraphColor='#f39c5b';
export const DivColor='#fff';
export const ReportCardColor='linear-gradient(to top, #fdab3b , #fdab3b)';
export const ReportCardBoundaryColor='#002663';