export const HeaderColor = '#3f2c37';
export const HeaderFontColor = '#fff!important';
export const SidebarColor = '#3f2c37';
export const CardBottom = 'linear-gradient(to right, #f39c5b , #f87c1f)';
export const SubmitButton = '#f39c5b';
export const SubmitGradientButton ='linear-gradient(to top, #3f2c37 , #f87c1f)';
export const AppNameAdmin="Liwach Portal";
export const TitleColor = '#f87c1f';
export const text="#f87c1f"
export const TitleSize = 50;
export const CardTitleColor = '#f39c5b';
export const GraphColor='#f39c5b';
export const DivColor='#fff';
export const ReportCardColor='linear-gradient(to top, #3f2c37 , #f87c1f)';
export const ReportCardBoundaryColor='#3f2c37';