export const HeaderColor = '#3f2c37';
export const HeaderFontColor = '#fff!important';
export const SidebarColor = '#3f2c37';
export const CardBottom = 'linear-gradient(to right, #c2b2b4 , #c2b2b4)';
export const SubmitButton = '#c2b2b4';
export const SubmitGradientButton ='linear-gradient(to top, #c2b2b4 , #c2b2b4)';
export const AppNameAdmin="Liwach Portal";
export const TitleColor = '#c2b2b4';
export const text="#f87c1f"
export const TitleSize = 50;
export const CardTitleColor = '#c2b2b4';
export const GraphColor='#f39c5b';
export const DivColor='#fff';
export const ReportCardColor='linear-gradient(to top, #c2b2b4 , #c2b2b4)';
export const ReportCardBoundaryColor='#3f2c37';